### ISSUE TITLE
The QR Code not render correctly in gitbook 3.2.3

### ISSUE THREAD

**Issue by kylinsoong** [aleen42/gitbook-footer#10] opened 2018-06-06 08:06 UTC
With #9 setting build with gitbook 3.2.3 and found that the QR code not render correctly, it show a list of mess code, as below:
~~~
<footer class="footer"><div class="footercontainer—​normal" alt=" https://aleen42.gitbooks.io/personalwiki/content/linux/ "> <img src="data:image/gif;base64,R0lGODdhqgCqAIAAAAAAAP///ywAAAAAqgCqAAAC/4yPqcvtD6OctNqLs968+w+G4kiW5omm6sq27gvH8kzX9u0C+s7zhn8AKnSMnnH3QwYBCGLAmHQCncko83mtYqmL45HihW6z4yK5GZ4qtVqxWkqGw9FWR1oY4Q6vcr5/3qBXNnb3t/bgdja4p8bWpWgHudSm1Oe4x2hYaCVo1piAh/bZOTnRB0iZKIFniVUHevjKhbpIGFt66gemqYv75Zp32NoqqvhJWVwc6svZu8p7WZosDZyJfDEbZ2zoKJidWilp1hwdzart2UsK8U0N3r1NB6xqCl0NC5799ms9z++fplkiQF7yOQtG7p68XMp4LZPlEJ2tgWEgClTXo1wgcf/3CP6iZc5eQFjH3C3xhjFkpF0rmU1MiS8mRTENVT5CeQ3nxl2b/OWE6fGnUJ9EgxYFirTns55GmyId6hTq06NSL9IsQatdv4WSKL6ymfVWpnUxwsrb6nIst1o6w5JNaIKU0pfXrK49h3buz3N8OT5E1PVOQ6N2IWo9qW0kV7i2pqWzcJisx5LwHgMMt+zw4MBM7bGkJhkj5Y6cRWO+pRnx30KTxQKmN06mxHbDPlY0OSpxRty7LWKz3XJx2qO5igvbRpgu774an4XUtxYTUY0FlU/7e5Yk8t06MYBkezq22Zvc/xnmSB018JjeYWZHa9crYumhaesen/k4dsB1TTr/Vi0YeG35dRw8JREzH4A83ebbPlx9B5uAulWmXW1f7dRYBXPlhqCFFR7EXIKpyYegeL39xhB7svm2GUqRMZjhSLkx5mAG+3S34iAumgdei/dF5GGK53HQ14HhvCMbh7PdVSBors1IWoka6lfedabRV2WPl134olxHTqejayYylp1iUT5JII5SCndVa9U1h6GQKpoJnZeRqBndIwaxGSCcY5K342o8blbmhAmSOVyNeB2KkEIKfujlVWq9+F+RgRnIZJfozRlRQtDFRyWU+bF26ZlvftgfO0vOBOJpdK4nJal2mjpojAepmqqtNLY6GpKv4vlWhp6i+RmEWbbJ65dY/xr3KafBIlujdETa9t2fJG56LaZ1sjZsoR5U16uel3l4Z3hgQitrt04u2B+U3mrnY7OViqmrL4I2uGk/brm3LrwAopsXvRHK+SC/CxJ8LpPPwQojqO/Zq6x/YWrAKpYF5yojkNudOmuE6VXb6H57bWwaqefFuiqx5PF5Kq61WKuekiaHGW2/kkq8KLP5vtbwo/ZtSG3QnRUM7o962dgnqqSBuq3OTEes874zt2eTvkbfOm6oX47Ys6WjyTtl1f42jbVxhCY8acxXG/vfUsduhyTMFLbsaHLLqmfxxCi+bfWFeePH44BwIiy43p89vOjFwy2c7eJn+ppy4cEiDjdvXP+WTbKiS0qrt5GI2s0fpObKl07GLkd9ItimvxRucP+OXl59AT5bctKq34a6n+Jq6jnEFw3bGqaM461i6bWeLtHvS/uuXONGGnszjsbf7LaPw3MufNbAoxki3U8jyu7r0BNfqJsinViTiLXOTD3SlDK6J+tJVyVxYWCe7CrW4VPot/bym0m/weEOc2arl3Pklz7jtSRnnXqZSzSFvcc5SndESx36lGYi+yjvXmiDX90MNasDRnCDAlOZ5gbkFITNLUtqOVzxXte/tjGvZpCDHAfjFyl6/U1/WbMU/5a3n9QIcFsrdFc9hnI3dI2niAR62BB/xETQQaZJ+bFS4iaIRRn/ouxyTqSVEKf0s3io74oh3AgKxUjGUimPgruL2AHPuKMKtquEQ7PZAEXWRpAtEI0XZKARg8it5RnkRjuroejIVkASRmVLPQShG814vJA98ldC01qQklK7ZrXukIUElCOFY8jtKWleIeqbBLvHwmCgEpSMJGLz8uRDD+LLio7cpNXAdrnbfTGWa8IgJDvWwCl2SG2kNNTHoMjIctGOg4kEY+zON8I4acyULlNXHJO0uSx6sjZf66T5RsVDztHjmopDYj30CENxcZFWg0ze/dLJTc9oSZjhTKc4qYjMZmpwm1eiGZW6GL5S1u9/2bzWMLNnvdABzH2wJB8/Gbi9ISVK/23tk6MsVZkmPgJQmyxqYwINN88XrrM9skti4LD1SFYu9HaxCRhJK9dOWeFzpPbE5j6nhsVeqoqcjZTpTZt0NpOyzHalwmM0NXnH/BVtjiZdZNo6ij90HrWWlfweVSz3ylwpkoANnJzPiLqvqFpwmLIbJzI7ulGvivIfz8sUjGoGyKWyU30JBagnr/dVauZ1r8HjFOW4FkG1GvBR6rJSC+eaQjH+kKZiYyMOM/k2zcXvjVvLU1CV1leq1St3/hPVBfeY2OmVJrQbACxB7yY2mTkUWJFtaKB0iCGwzK+Viu3cSSl3tnhqMZKgne0JLTnAdynzpBC16TM1i1OJKnF27v9cZtcsKNuiCVaBAz2sWV+LWgdGz7I4K00MzwlUjKYIZVX052HLKdKcmsuFl/VpIDPLTxE+8LN7jWY1RRcv92JyuF6VHH0Lm17X+ZeQHIOawT5ILgfOEY/ea5Rs11pgwDXWvBLMG/jw+xsAx5N0dixrPym53QJecYoadiuHmThcG7L1uSIOLz3DaNaFtRSryWFbv9IHTKjyDMZ8Q7AaacwvGy92sEN1LEGv2UsawrOyf80nV7Prup36trI5/K50gwzTzWY5brEF74Q/iiypkNawXhwt997aSR17GMxT8SySkyWo9gGNxIjN6K6+OVaH2u+juH2nVD1a35UJy7Ygru3/ngn7QtD9mbqT5aT5+izgVqnUwMfUsdt4LFrVQrrLS0yYhAVtS06fWbiCdNIW57vO8ha4XNOSIU3fVz7u/jTVxFs1JDUb3TxTEr3SO+3Ympssy1DMne3ML0tDOrwQS3qiVS4tlXucvYWSkMsCvXMT/cVYnhW7g/grppuNqd08R1lCdg2YUxHNTCy3d2fbRas8jVxMc1pbbqW2tZTPGEVDgzetxMRsPxnta69Ncj0I5aij+73bb6dYfOtFoI97l+1xsxrda6OorJfNZTKncZQGLze2B41Ii/ev00l+dqz7Ot25Qhli72uxu+u65EMzNWyIRm+jf3pdjDs8t9PMEbzV/+k/+HxwxtVWcI7ODTJCfity3k30j4vO4DYvu9kV3XH+7snL2S4805VLt8M6cGXWuvJoW39o102osZQPW7csx1yJjb1l9fLcwliBHaaHPtiQg3Oqc/e5M1f3LjyPrJuhEXM2Y53xvwfXr8TpsVxdjepk+vmTRpcv1vUM6ElvG5fa5DgrC37fy/ea7jN3uQdLKnmMgRt5bZ3XVqU9RjgnVc1pT2WxUinQFkf47FKbPUhjSnCae8zqVa9Y27XVM1rzN/mSDHV+Fx7mvAfSpZ1PV4aJDMTwfhudZEN+Lhtua6MaN7UN1Tg0RT2w4361+8xjLzZXyPf5Fg7CKeV246Nv+VD3Zz/+I6M7q8JFcpD1RVwXV6t3dPV0S0+nfrpTY2lmdgUIeQGEUVbmZAMYeT+HAxmogRvIgR3ogR8IgiEogiNIgiVogieIgimogivIghxYAAA7" width="170" height="170"/> <div class="footerdescription—​normal"><p class="paragraph footerauthor—​normal" style="color: #000 !important;">Aleen<sup class="super">®</sup></p><p class="paragraph footerquote—​normal" style="color: #000 !important;">More than a coder, more than a designer</p><div class="footermain—​normal"><p class="paragraph footermainparagraph—​normal copyright" style="color: #666 !important;">Copyright © aleen42 all right reserved, powered by <a href="https://github.com/aleen42" target="_blank">aleen42</a></span><p class="paragraph footermainparagraph—​normal footermodifyTime—​normal" style="color: #666 !important;"><span style="color: #666 !important;">modified at</span> 2018-06-01 09:29:15 </p></div></div></div><div class="box__issues"> <span class="issue-line"><p class="issue-header"><strong>8</strong> issues reported</p></span><p class="issues">#32 <a href="https://github.com/aleen42/PersonalWiki/issues/32" target="_blank">[集] A collection of confusing problems met when developing JavaScript under IE</a><span style="margin-left: 10px; color: #ddd;">2018-05-31 23:53:14</span><span class="issue-label" style="background-color: #fbca04; color: #ffffff;">Tasks!</span></p> <p class="issue-edge"></p><p class="issues">#30 <a href="https://github.com/aleen42/PersonalWiki/issues/30" target="_blank">[思] 当需要传递多个不定参数时，该如何设计 JavaScript 函数？</a><span style="margin-left: 10px; color: #ddd;">2017-05-29 17:42:07</span><span class="issue-label" style="background-color: #D15A0D; color: #ffffff;">Inspiration!</span></p> <p class="issue-edge"></p><p class="issues">#29 <a href="https://github.com/aleen42/PersonalWiki/issues/29" target="_blank">[歸納] 304 Status Code 下的头部信息</a><span style="margin-left: 10px; color: #ddd;">2018-03-19 20:25:21</span><span class="issue-label" style="background-color: #000000; color: #ffffff;">Communication!</span><span class="issue-label" style="background-color: #FFFFF0; color: #000000;">Summary!</span></p> <p class="issue-edge"></p><p class="issues">#28 <a href="https://github.com/aleen42/PersonalWiki/issues/28" target="_blank">[歸納] 你以为 JavaScript 没数据结构么？</a><span style="margin-left: 10px; color: #ddd;">2018-03-19 20:25:04</span><span class="issue-label" style="background-color: #000000; color: #ffffff;">Communication!</span><span class="issue-label" style="background-color: #FFFFF0; color: #000000;">Summary!</span></p> <p class="issue-edge"></p><p class="issues">#27 <a href="https://github.com/aleen42/PersonalWiki/issues/27" target="_blank">[歸納] JavaScript 之高性能</a><span style="margin-left: 10px; color: #ddd;">2018-03-19 20:24:53</span><span class="issue-label" style="background-color: #000000; color: #ffffff;">Communication!</span><span class="issue-label" style="background-color: #FFFFF0; color: #000000;">Summary!</span></p> <p class="issue-edge"></p><p class="issues">#26 <a href="https://github.com/aleen42/PersonalWiki/issues/26" target="_blank">Microtasks? Macrotasks?</a><span style="margin-left: 10px; color: #ddd;">2017-02-27 02:05:36</span><span class="issue-label" style="background-color: #000000; color: #ffffff;">Communication!</span></p> <p class="issue-edge"></p><p class="issues">#25 <a href="https://github.com/aleen42/PersonalWiki/issues/25" target="_blank">gitbook-edit plugin ignores book.json root configuration element</a><span style="margin-left: 10px; color: #ddd;">2017-02-25 02:53:37</span><span class="issue-label" style="background-color: #000000; color: #ffffff;">Communication!</span></p> <p class="issue-edge"></p><p class="issues">#24 <a href="https://github.com/aleen42/PersonalWiki/issues/24" target="_blank">[譯] Align SVG Icons to Text and Say Goodbye to Font Icons</a><span style="margin-left: 10px; color: #ddd;">2017-02-07 18:39:42</span><span class="issue-label" style="background-color: #fbca04; color: #ffffff;">Translations!</span></p>

</div></footer>
~~~

**Comment by aleen42** [comment] 2018-06-06 10:35
I have used GitBook@3.2.3 to build with your configuration, and cannot reproduce the problem here. Here is the result I have built:

![image](https://user-images.githubusercontent.com/9573300/41033220-4de0bbd2-69b8-11e8-8193-c472d10fdfe5.png)

**Comment by aleen42** [comment] 2018-06-06 10:41
Actually, it is welcome to fork my project, and debug it by setting it as your GitBook dependencies like following snippet:

```json
"dependencies": {
  ""gitbook-plugin-page-footer": "aleen42/gitbook-footer"
}
```

**Comment by aleen42** [comment] 2018-11-27 09:01
As there is no any more information for reproducing the problem, I am going to close this issue. Feel free to reopen it when meeting the same problem.

**Closed by aleen42** 2018-11-27 09:01 UTC
